set(FVTKHDF_DISPLAY_VERSION "${PROJECT_VERSION}-dev")

find_package(Git QUIET)
if(Git_FOUND AND EXISTS "${PROJECT_SOURCE_DIR}/.git")
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" describe --tags --exact-match
    WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}"
    RESULT_VARIABLE FVTKHDF_GIT_TAG_RESULT
    OUTPUT_VARIABLE FVTKHDF_GIT_TAG
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
  )
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" rev-parse --short HEAD
    WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}"
    RESULT_VARIABLE FVTKHDF_GIT_SHA_RESULT
    OUTPUT_VARIABLE FVTKHDF_GIT_SHA
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
  )
  if(FVTKHDF_GIT_TAG_RESULT EQUAL 0 AND FVTKHDF_GIT_TAG STREQUAL "v${PROJECT_VERSION}")
    set(FVTKHDF_DISPLAY_VERSION "${PROJECT_VERSION}")
  elseif(FVTKHDF_GIT_SHA_RESULT EQUAL 0 AND NOT FVTKHDF_GIT_SHA STREQUAL "")
    string(APPEND FVTKHDF_DISPLAY_VERSION "+g${FVTKHDF_GIT_SHA}")
  endif()
endif()
