name: CI

on: [push, pull_request]

jobs:
  build-test:
    name: Build & Test (Ubuntu/GFortran)
    runs-on: ubuntu-latest
    container: ghcr.io/${{ lower(github.repository) }}/fvtkhdf-ci:latest
    
    strategy:
      fail-fast: false
      matrix:
        mpi: [ON, OFF]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure CMake
      run: |
        if [ "${{ matrix.mpi }}" == "ON" ]; then
          export CC=mpicc
          export FC=mpif90
        fi
        cmake -B build \
          -DCMAKE_BUILD_TYPE=Debug \
          -DENABLE_MPI=${{ matrix.mpi }}

    - name: Build
      run: cmake --build build --parallel 2

    - name: Run Tests
      working-directory: build
      env:
        # Allow running 4 processes on a 2-core machine
        OMPI_MCA_rmaps_base_oversubscribe: 1
      run: ctest --output-on-failure
